board/urls.py
from django.urls import path, include
from . import views # .은 현재위치다

app_name = "board"

urlpatterns = [
    path('', views.setData, name='setData'),
    path('select',views.selectBoard,name='select'),
    path('man', views.man, name='man'),
    path('suggest', views.suggest, name='suggest'),
]

flowerRoad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('members/', include('members.urls')),
    path('board/', include('board.urls')),
    path('admin/', admin.site.urls),
]

members/urls.py
from django.urls import path, include

from . import views # .은 현재위치다.

app_name = "members"

urlpatterns = [
    path('', views.setDatad, name='setDatad'),
    path('man', views.man, name='man'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('mini', views.mini, name='mini'),
    path('pot', views.pot, name='pot'),
    path('main', views.main, name='main'),
    path('diorama', views.diorama, name='diorama'),
    #path('userid=<userid>&userpw=<userpw>&phone=<phone>&date=<date>&addr=<addr>&gend=<gend>', views.addUser, name='addUser')
    #path('userid=<userid>&userpw=<userpw>', views.login, name='login'),
    #path('userid=<userid>', views.checkUser, name='check')

]

board/models.py
from django.db import models
from django.utils import timezone
from members.models import User

# Create your models here.


class BoardData(models.Model):
    objects = models.Manager()
    board_number = models.AutoField(null=False, primary_key=True)
    board_title = models.CharField(max_length = 126, null=False)
    board_content = models.TextField(null=False)
    board_writer = models.ForeignKey(User, on_delete=models.CASCADE)
    board_date = models.CharField(max_length=140)
  
    
    def __str__(self):
        return super().__str__()

        

members/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    objects = models.Manager()
    userid=models.CharField(max_length=20, primary_key=True)
    userpw=models.CharField(max_length=20)
    phone_num=models.CharField(max_length=30)
    birth_date=models.DateField()
    addr=models.TextField()
    gender=models.CharField(max_length=20)
    email=models.CharField(max_length=40, null=True)

    def __str__(self):
        return self.userid

board/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, JsonResponse
from django.urls import path, include
from members.models import User
from .models import BoardData
from datetime import datetime
from django.shortcuts import render


def setData(request):
    req_code = request.GET.get("req_code")
    if req_code is not None:
        if req_code == "board_write":
            board_title = request.GET.get("title")
            board_content = request.GET.get("content")
            userid = request.GET.get("userid")
            board_writer = User.objects.get(userid=userid)
            board_date = getNow()

            try:
                addData = BoardData(board_title=board_title, board_content=board_content, board_writer=board_writer,
                                    board_date=board_date)
                addData.save()
            except Exception as err:
                # return HttpResponse("Fail")
                return HttpResponse("Fail")
            return HttpResponse("Success")
        elif req_code == "board_search":
            myresult =BoardData.objects.all()
            return HttpResponse("김진영 ㅎㅇ")
    else:
        return HttpResponse("해당하는 REQ_CODE가 없거나 누락되어있습니다...")

    return HttpResponse("Hello Django~!")


def getNow():
    now = datetime.now()
    y_m_d = str(str(now.year) + "-" + str(now.month) + "-" + str(now.day))
    h_m_s = str(str(now.hour) + ":" + str(now.minute) + ":" + str(now.second))
    date = str(y_m_d + " " + h_m_s)
    return date


def selectBoard(request) : 
    myresult =BoardData.objects.all()
    return HttpResponse(myresult[0].board_title +' ' +myresult[0].board_content +' ' +myresult[0].board_date)


def man(request):
    return render(request, "board/board_manager.html", {})


def suggest(request):
    return render(request, "board/suggest.html", {})

members/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.urls import path, include
from .models import User


def setDatad(request):
    req_code = request.GET.get("req_code")
    if req_code is not None:
        if req_code == "find":
            try:
                userid = request.GET.get("userid")
                print(userid)
                data = User.objects.get(userid=userid)
            except Exception as err:
                return HttpResponse(str(err))  # 중복 아이디가 없으므로 사용가능
            return HttpResponse("Fail")  # 중복 아이디가 있습니다
        elif req_code == "login":
            try:
                userid = request.GET.get("userid")
                userpw = request.GET.get("userpw")
                data = User.objects.get(userid=userid, userpw=userpw)
            except Exception:
                return HttpResponse("Fail")
            return HttpResponse("Success")
        elif req_code == "user_create":
            try:
                userid = request.GET.get("userid")
                userpw = request.GET.get("userpw")
                phone = request.GET.get("phone")
                phone = changeNum(phone)
                birth_date = request.GET.get("date")
                birth_date = changeBirth(birth_date)
                addr = request.GET.get("addr")
                gender = request.GET.get("gend")
                email = request.GET.get("email")
                if email is None:
                    addData = User(userid=userid, userpw=userpw, phone_num=phone, birth_date=birth_date, addr=addr,
                                   gender=gender)   
                else:
                    addData = User(userid=userid, userpw=userpw, phone_num=phone, birth_date=birth_date, addr=addr,
                                   gender=gender, email=email)
                addData.save()
            except Exception:
                return HttpResponse("Fail")
            return HttpResponse("Success")
    else:
        return HttpResponse("해당하는 REQ_CODE가 없거나 누락되어있습니다...")
    return HttpResponse("Hello Django~!")


def changeNum(phone):
    front = phone[0:3]
    mid = phone[3:7]
    end = phone[7:]

    phone = front + '-' + mid + '-' + end
    return phone


def changeBirth(birth_date):
    year = birth_date[:4]
    month = birth_date[4:6]
    day = birth_date[6:]

    birth_date = year + '-' + month + '-' + day
    return birth_date

    
# 향후 구현예정 회원가입 후 이메일 인증 구현 SMTP
def man(request):
    return render(request, "members/mem_manager.html", {})


def login(request):
    return render(request, "members/login.html", {})


def register(request):
    return render(request, "members/userlog.html", {})

    
def mini(request):
    return render(request, "members/mini.html", {})


def pot(request):
    return render(request, "members/pot.html", {})


def main(request):
    return render(request, "members/main.html", {})

def diorama(request):
    return render(request, "members/diorama.html", {})

board/templates/board/board_manager.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>


<h1>게시글 쓰기 테스트</h1>
아이디 <input type="text" name="userid" id="write_userid" /> <br />
게시판 제목 <input type="text" name="title" id="write_title" /> <br />
게시판 내용 <input type="textarea" width="500" height="500" name="content" id="write_content" /> <br />
<input type="button" id="write" value="눌러" /> <br />
<hr />

<h1>게시글 조회 테스트</h1>
<input type="button" id="select" value="눌러" /> <br />
<hr />

<script>  
    $('#write').click(function() {
        $.ajax({
        type : 'GET',
        dataType : 'text',
        url : "{% url 'board:setData' %}",
        data : {
            userid : $('#write_userid').val(),
            title : $('#write_title').val(),
            content : $('#write_content').val(),
            req_code : "board_write"
        },
        cache : false,
        success : function(data) {
            alert(data);
        },
        error : function(e) {
            alert('error');
        }
        });
    });

    $('#select').click(function() {
        $.ajax({
        type : 'GET',
        dataType : 'text',
        url : "{% url 'board:setData' %}",
        data : {
            req_code : "board_search"
        },
        cache : false,
        success : function(data) {
            alert(data);
        },
        error : function(e) {
            alert('error');
        }
        });
    });
</script>

board/templates/board/suggest.html
{% load static %}

<!DOCTYPE html>

<html lang="ko">

<head>
    <title>소담</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>

<body>
    <!-- Header -->
    <header id="header">
            <div class="inner">
                <a href="{% url 'members:main' %}" class="logo"><img src="/static/image/logo2.png"></a>
                <nav id="nav">
                    <a href="{% url 'members:main' %}">홈</a>
                    <a href="{% url 'board:suggest' %}">제안요청</a>
                </nav>
                <a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
            </div>
        </header>

    <footer id="footer">
        <div class="inner">
            
            <h3>제안하기</h3>

            <form action="#" method="post">

                <div class="field half first">
                    <label for="name">제목</label>
                    <input name="name" id="name" type="text" placeholder="제목"">
                </div>
                <div class="field half">
                    <select>
                        <option value="1" selected disabled>제품종류</option>
                        <option value="1">디오라마</option>
                        <option value="2">항아리</option>
                        <option value="3">미니</option>
                        <option value="4">그 외</option>

                    </select>
                </div>
                <div class="field">
                    <label for="message">제안내용</label>
                    <textarea name="message" id="message" rows="6" placeholder="예상금액: XXXX&#13;&#10;완성품을 받아보실 날짜: XXXX&#13;&#10;........""></textarea>
                </div>
                <ul class="actions">
                    <li><input value="제안내용 전송" class="button alt" type="button" onclick="suggest_submit()" ></li>
                </ul>
            </form>

            <div class="copyright">
                &copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
            </div>

        </div>
    </footer>

    <script>
        function suggest_submit() {
            alert("문의가 완료되었습니다");
            location.href = "{% url 'members:main' %}";
        }
    </script>
</body>
</html>

members/templates/members/diorama.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : PlainLeaf 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130902

-->
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title></title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet" />
	<link href="{% static 'css/diorama.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all" />

	<!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->

</head>

<body>
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="{% url 'members:diorama' %}">디오라마(Diorama)</a></h1>
		</div>
		<div id="menu">
			<ul>
				<li class="active"><a href="{% url 'members:main' %}" accesskey="1" title="">홈</a></li>
				<li accesskey="3" title=""><a href="{% url 'board:suggest' %}">제안요청</a></li>
				<ul>
					<div class="dropdown">
						<li class="dropbtn" accesskey="3" title="">타 제품</li>
						<div class="dropdown-content">
							<a href="{% url 'members:pot' %}">항아리</a>
							<a href="{% url 'members:mini' %}">미니</a>
						</div>
					</div>
				</ul>
			</ul>
		</div>
	</div>

	<div id="banner"></div>
	<div class="banner-text">
		<p class="text-header">디오라마</p>
		<p class="text-body">배경을 그린 막 앞에 여러 가지 물건을 배치하고 </br>그것을 잘 조명하여 입체적인 실물감이 나게 하는 장치</p>
	</div>
	<div id="page" class="container">
		<div class="boxA">
			<h2>제</h2>
			<div class="box">
				<a href="#" class="image image-full"><img src="/static/image/D1.png" alt="" /></a>
			</div>
			<p>제품설명1</p>
			<a href="#" class="button">자세히 보기 및 구매</a>
		</div>

		<div class="boxB">
			<h2>품</h2>
			<div class="box">
				<a href="#" class="image image-full"><img src="/static/image/D2.png"  alt="" /></a>

			</div>
			<p>제품설명2</p>
			<a href="#" class="button">자세히 보기 및 구매</a>
		</div>

		<div class="boxC">
			<h2>칸</h2>
			<div class="box">
				<a href="#" class="image image-full"><img src="/static/image/D3.png" alt="" /></a>

			</div>
			<p>제품설명3</p>
			<a href="#" class="button">자세히 보기 및 구매</a>
		</div>
	</div>
	<div id="copyright" class="container">
		<p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by
			<a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
	</div>
	</div>
</body>

</html>

members/templates/members/login.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>로그인</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>

<body>
    <form class="login-form" style="padding: 45px;" action="javascript:void(0);">
        <h1 >Login</h1>
        <div class="form-field">
            <i class="fas fa-user"></i>
            <input type="text" name="userid" id="username" class="form-field" pattern="^[a-zA-Z0-9_-]{1,16}$"
                placeholder=" " required>
            <label for="username">Username</label>
        </div>
        <div class="form-field">
            <i class="fas fa-lock"></i>
            <input type="password" name="userpw" id="password" class="form-field" placeholder=" " required>
            <label for="password">Password</label>
        </div>
        <button type="submit" value="Login" class="btn" onclick="ckbox()">Login</button>
        <button type="button" value="회원가입" class="btn"onclick="go_register()" >회원가입</button>
    </form>

</body>
<script>
    function go_register() {
        location.href="{% url 'members:register' %}"
    }

    function ckbox() {
        $.ajax({
        type : 'GET',
        dataType : 'text',
        url : "{% url 'members:setData' %}",
        data : {
            userid : $('#username').val(),
            userpw : $('#password').val(),
            req_code : "login"
        },
        cache : false,
        success : function(data) {
            alert(data);
            if(data == "Success") {
                location.href = "{% url 'members:main' %}"
            }
        },
        error : function(e) {
            alert('error');
        }
    });
    }

    function register() {
        location.href = "{% url 'members:register' %}";
    }
</script>

</html>

members/templates/members/main.html
{% load static %}

<!DOCTYPE HTML>
<!--
	Projection by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>소담</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<div class="inner">
					<a href="{% url 'members:main' %}" class="logo"><img src="/static/image/logo2.png"></a>
					<nav id="nav">
						<a href="{% url 'members:main' %}">홈</a>
						<a href="{% url 'board:suggest' %}">제안요청</a>
					</nav>
					<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
				</div>
			</header>

		<!-- Banner -->
			<section id="banner">
				<div class="inner">
					<header>
						<h1>Welcome to 꽃길</h1>
					</header>

					<div class="flex ">

						<div >
							<span class="icon fa-car"></span>
							<h3><a href="{% url 'members:diorama' %}">디오라마</a></h3>
							<p>Suspendisse amet ullamco</p>
						</div>

						<div>
							<span class="icon fa-camera"></span>
							<h3><a href="{% url 'members:mini' %}">미니어처</a></h3>
							<p>Class aptent taciti ad litora</p>
						</div>

						<div>
							<span class="icon fa-bug"></span>
							<h3><a href="{% url 'members:pot' %}">항아리</a></h3>
							<p>Nulla vitae mauris non felis</p>
						</div>

					</div>

					<footer>
						<a href="{% url 'members:login' %}" class="button">로그인</a>
					</footer>
				</div>
			</section>


		<!-- Three -->
			<section id="three" class="wrapper align-center">
				<div class="inner">
					<div class="flex flex-2">
						<article>
							<div class="image round">
								<img src="/static/image/pic1.png" alt="Pic 01" />
							</div>
							<header>
								<h3>제품 제작 모습</h3>
							</header>
							<p>제작모습 설명</p>
							<footer>
								<a href="#" class="button">제작과정 보기</a>
							</footer>
						</article>
						<article>
							<div class="image round">
								<img src="/static/image/review.png" alt="" />
							</div>
							<footer>
								<a href="#" class="button">전체 리뷰 보러가기</a>
							</footer>
						</article>
					</div>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<h3>문의</h3>

					<form action="#" method="post">

						<div class="field half first">
							<label for="name">Name</label>
							<input name="name" id="name" type="text" placeholder="Name">
						</div>
						<div class="field half">
							<label for="email">Email</label>
							<input name="email" id="email" type="email" placeholder="Email">
						</div>
						<div class="field">
							<label for="message">Message</label>
							<textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
						</div>
						<ul class="actions">
							<li><input value="Send Message" class="button alt" type="submit"></li>
						</ul>
					</form>

					<div class="copyright">
						&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
					</div>

				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

members/templates/members/mem_manager.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<h1>find 테스트</h1>
아이디 <input type="text" name="userid" id="find_userid" /> <br />
<input type="button" id="find" value="눌러" /> <br />
<hr />

<h1>login 테스트</h1>
아이디 <input type="text" name="userid" id="login_userid" /> <br />
비번<input type="text" name="userpw" id="login_userpw" /> <br />
<input type="button" id="login" value="눌러" /> <br />
<hr />

<h1>register 테스트</h1>
아이디 <input type="text" name="userid" id="register_userid" /> <br />
비번 <input type="text" name="userpw" id="register_userpw" /> <br />
전화번호 <input type="text" name="phone" id="register_phone" /> <br />
생년월일 <input type="text" name="date" id="register_date" /> <br />
주소 <input type="text" name="addr" id="register_addr" /> <br />
성별 <input type="text" name="gend" id="register_gend" /> <br />
이메일 <input type="text" name="email" id="register_email" /> <br />
<input type="button" id="register" value="눌러" /> <br />

<script>  
    $('#find').click(function() {
        $.ajax({
        type : 'GET',
        dataType : 'text',
        url : "{% url 'members:setData' %}",
        data : {
            userid : $('#find_userid').val(),
            req_code : "find"
        },
        cache : false,
        success : function(data) {
            alert(data);
        },
        error : function(e) {
            alert('error');
        }
        });
    });

    $('#login').click(function() {
        $.ajax({
        type : 'GET',
        dataType : 'text',
        url : "{% url 'members:setData' %}",
        data : {
            userid : $('#login_userid').val(),
            userpw : $('#login_userpw').val(),
            req_code : "login"
        },
        cache : false,
        success : function(data) {
            alert(data);
        },
        error : function(e) {
            alert('error');
        }
        });
    });

    $('#register').click(function() {
        $.ajax({
        type : 'GET',
        dataType : 'text',
        url : "{% url 'members:setData' %}",
        data : {
            userid : $('#register_userid').val(),
            userpw : $('#register_userpw').val(),
            phone : $('#register_phone').val(),
            date : $('#register_date').val(),
            addr : $('#register_addr').val(),
            gend : $('#register_gend').val(),
            email : $('#register_email').val(),
            req_code : "user_create"
        },
        cache : false,
        success : function(data) {
            alert(data);
        },
        error : function(e) {
            alert('error');
        }
        });
    });
</script>

members/templates/members/mini.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : PlainLeaf 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130902

-->
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title></title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet" />
	<link href="{% static 'css/mini.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all" />

	<!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->

</head>
	<body>
		<div id="header" class="container">
			<div id="logo">
				<h1><a href="{% url 'members:diorama' %}">미니(Mini)</a></h1>
			</div>
			<div id="menu">
				<ul>
					<li class="active"><a href="{% url 'members:main' %}" accesskey="1" title="">홈</a></li>
					<li accesskey="3" title=""><a href="{% url 'board:suggest' %}">제안요청</a></li>
					<ul>
						<div class="dropdown">
							<li class="dropbtn" accesskey="3" title="">타 제품</li>
							<div class="dropdown-content">
								<a href="{% url 'members:diorama' %}">디오라마</a>
								<a href="{% url 'members:pot' %}">항아리</a>
							</div>
						</div>
					</ul>
				</ul>
			</div>
		</div>
	<div id="banner"></div>
	<div id="page" class="container">
		<div class="boxA">
			<h2>Etiam posuere augue</h2>
			<div class="box">
				<a href="#" class="image image-full"><img src="/static/images/pic01.jpg" alt="" /></a>
				<span>Maecenas luctus lectus</span>
			</div>
			<p>제품설명1</p>
			<a href="#" class="button">Etiam posuere</a>
		</div>

		<div class="boxB">
			<h2>Donec dictum metus</h2>
			<div class="box">
				<a href="#" class="image image-full"><img src="/static/images/pic02.jpg" alt="" /></a>
				<span>Lorem ipsum dolor sit amet</span>
			</div>
			<p>제품설명2</p>
			<a href="#" class="button">Etiam posuere</a>
		</div>

		<div class="boxC">
			<h2>Fusce ultrices fringilla</h2>
			<div class="box">
				<a href="#" class="image image-full"><img src="/static/images/pic03.jpg" alt="" /></a>
				<span>Pellentesque quis lectus</span>
			</div>
			<p>제품설명3</p>
			<a href="#" class="button">Etiam posuere</a>
		</div>
	</div>
	
	<div id="copyright" class="container">
		<p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by
			<a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
	</div>
	</div>
</body>

</html>

members/templates/members/pot.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : PlainLeaf 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130902

-->
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title></title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet" />
	<link href="{% static 'css/pot.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all" />

	<!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->

</head>

<body>
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="{% url 'members:diorama' %}">항아리(Pot)</a></h1>
		</div>
		<div id="menu">
			<ul>
				<li class="active"><a href="{% url 'members:main' %}" accesskey="1" title="">홈</a></li>
				<li accesskey="3" title=""><a href="{% url 'board:suggest' %}">제안요청</a></li>
				<ul>
					<div class="dropdown">
						<li class="dropbtn" accesskey="3" title="">타 제품</li>
						<div class="dropdown-content">
							<a href="{% url 'members:diorama' %}">디오라마</a>
							<a href="{% url 'members:mini' %}">미니</a>
						</div>
					</div>
				</ul>
			</ul>
		</div>
	</div>
	<div id="banner"></div>
	<div id="page" class="container">
		<div class="boxA">
			<h2>Etiam posuere augue</h2>
			<div class="box">
				<a href="#" class="image image-full"><img src="/static/images/pic01.jpg" alt="" /></a>
				<span>Maecenas luctus lectus</span>
			</div>
			<p>제품설명1</p>
			<a href="#" class="button">Etiam posuere</a>
		</div>

		<div class="boxB">
			<h2>Donec dictum metus</h2>
			<div class="box">
				<a href="#" class="image image-full"><img src="/static/images/pic02.jpg" alt="" /></a>
				<span>Lorem ipsum dolor sit amet</span>
			</div>
			<p>제품설명2</p>
			<a href="#" class="button">Etiam posuere</a>
		</div>

		<div class="boxC">
			<h2>Fusce ultrices fringilla</h2>
			<div class="box">
				<a href="#" class="image image-full"><img src="/static/images/pic03.jpg" alt="" /></a>
				<span>Pellentesque quis lectus</span>
			</div>
			<p>제품설명3</p>
			<a href="#" class="button">Etiam posuere</a>
		</div>
	</div>
	
	<div id="copyright" class="container">
		<p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by
			<a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
	</div>
	</div>
</body>

</html>